SConstruct
argp-standalone gets used on Systems with a C Library that doesn't have argp integrated (e.g. musl and uclibc)
=> Add support for argp-standalone

SConstruct
Those are typically use by Linux distro packagers to enforce their flag policies,
e.g. for Mageia:
```
CFLAGS="${CFLAGS:--O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4}" ; export CFLAGS ;
CXXFLAGS="${CXXFLAGS:--O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4}" ; export CXXFLAGS ;
FFLAGS="${FFLAGS:--O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4}" ; export FFLAGS ;
LDFLAGS="${LDFLAGS:- -Wl,--as-needed -Wl,--no-undefined -Wl,-z,relro -Wl,-O1 -Wl,--build-id -Wl,--enable-new-dtags}" ; export LDFLAGS
```
=> SCons: Append external environment flags

.gitignore, README.md, SConstruct, src/system.c
- instead of `-lasan -lubsan`, pass the sanitize flags to the final linking command, clang links these libraries automatically (and knows their actual location and name)
- ignore the unknown-warning-option warning from clang 5.0.0
- link to argp when libc is not glibc (might also help on musl systems like Alpine Linux?)
- check for `__unix__` instead of `__linux__` for GTK
Recent gcc is also [supposed to](https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html#index-static-libasan) automatically link `asan`/`ubsan` provided `-fsanitize` flags, but gcc 5.x doesn't, so keeping `-lasan -lubsan` for non-clang.
=> Fix build on FreeBSD (and probably other *BSD)

README.md
Congrats on the snap of Goxel. This adds a badge to show the current build status on snapcraft.io.
=> Add a snapcraft.io build status badge

src/formats/gox.c
This pull request sets a `visible` flag when saving and loading.
=> Save/Load `visible` flag for layers

index.markdown
Hello,
A member of the Debian french l10n team noticed a typo in the description of the package `goxel` that is also present in goxel's website. Here's a merge request to fix it.
Thanks for making goxel!
Thomas
=> Fix typo in ply format name

doc/cla/individual/ntfwc.md, src/tools/selection.c
I noticed that when a different pane is set, selection stops working correctly. It is not correctly determining the selection box dimensions and even introduces negative sizes. This pull request fixes the behavior to be consistent when different planes are set.
=> Selection fix for when different panes are set

src/gui/menu.c
It is a only a lost character.
=> Fixed a tiny typo mistake in the 'edit' menu entry 'Past' -> 'Paste' .

doc/cla/individual/sariug.md, src/formats/qubicle.c, src/main.c
Hello ! 
This pull request contains two things that I needed while I was using goxel. Would be nice to have it in the master too ! 
- Drag&drop: I was using multiple files(over 10). Opening them 1-by-1 was taking so long. Added drag and drop support. 
- While trying to import qb, I was by mistake selecting other types, and the program was acting like memory leak(the computer was stucking for a few minutes then goxel crushes). So added a qb file check. 
Looking forward to hear for any suggestions of these, or maybe merging :) 
Best regards,
=> drag&drop and qb file type check

SConstruct
Sort input file list
so that goxel builds in a reproducible way
in spite of indeterministic filesystem readdir order
and http://bugs.python.org/issue30461
(without this patch there were variations in `/usr/bin/goxel` machine code)
See https://reproducible-builds.org/ for why this is good.
This PR was done while working on [reproducible builds for openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds).
=> Sort input file list

src/formats/vxl.c
Fix for #52 
Bug was in scenes with 64 height voxel columns, where no voxels were touching air.
Function `is_surface` was not returning 1 while iterating on such column which was causing number of colors to be zero. This commit adds additional check for border voxels, which helps algorithm in such case. Z check prevents corrupted files, X and Y checks prevent not writing color for border voxels.
Can be tested with 512x512x64 filled region or with the project attached to mentioned issue
Also a small typo fix.
=> Fix vxl export with height 64

snap/gui/goxel.desktop
`Icon=${SNAP}/icon.png` is still obviously wrong, but I don't want to break the snapcraft package.
=> Completed the .desktop file

Makefile
`744` is a bit weird. On @openSUSE installing it via .rpm causes it to be not executable by the user.
=> Fixed binary execution permission

snap/gui/io.github.guillaumechereau.Goxel.appdata.xml
* Changed metadata license to `CC0-1.0`. Copyleft licenses are not supported here. (See https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-metadata_license)
* Removed screenshots (they return 404) and replaced them with a image from the gallery. (Is the image compatible with the CC0 license?)
* Updated the release version and date.
* Changed the homepage to https://goxel.xyz/
* Added age rating.
=> Update AppStream metadata

doc/cla/individual/ravencgg.md, src/image.c
Fixes a crash in the memcpy on non-square images.
Fixes the orientation and placement of the mesh.
=> Fix image plane to mesh conversion

snap/gui/goxel.desktop
This change gives a more uniform look when viewing the menu of available applications on Linux.
=> Use an uppercase letter for the Goxel desktop shortcut

src/formats/txt.c
empty lines were not accounted for, it makes it easier to manage when writing them by hand
=> fixed parsing of text files written by hand

.github/workflows/ci.yml, Makefile
https://stackoverflow.com/a/7045431/2278742
https://stackoverflow.com/questions/2527496/how-can-i-write-a-makefile-to-auto-detect-and-parallelize-the-build-with-gnu-mak#comment51509939_7045431
Now the CI log shows the following:
[windows_x86_64](https://github.com/Alexander-Wilms/goxel/actions/runs/7513436066/job/20455186036#logs)
```
Run make release
scons "-j 4" mode=release
```
[linux_x86_64](https://github.com/Alexander-Wilms/goxel/actions/runs/7513436066/job/20455185960#logs)
```
Run make release
scons "-j 4" mode=release
```
[osx_x86_64](https://github.com/Alexander-Wilms/goxel/actions/runs/7513436066/job/20455186002#logs)
```
Run make release
scons "-j 3" mode=release
```
The Stackoverflow answer linked above also recommends
```
NUMPROC := $(shell echo "$(NUMPROC)/2"|bc)
```
but …
=> Fix parallel build on all platforms

doc/cla/individual/madd-games.md, src/formats/png.c
Currently I get a segmentation fault on the following command:
```
goxel 0-colormap.vsp -e colormap.png
```
It turns out it's because `png_export()` calls for example `cache_get()` on `g_items_cache` which is `NULL`, because `render_init()` is never called. Normally when the GUI is initialized it gets called from `goxel_iter()` but this never happens with the `-e` option.
I have added this fix and confirmed it works in the `vsp` format which I added in my own branch. Unfortunately I cannot test this with imporing `.gox` because i get a different segmentation fault when i try `goxel test.gox -e test.png`, in the GOX importer, which I haven't figured out the cause of. But, it should be easy to see that we must initialize the renderer before we call `goxel_render_to_buf()`.
=> Initialize graphics context in png_export

INTERNALS.md, README.md
I noticed the explanation in `INTERNALS.md` is outdated and refers to "mesh" instead of "volume" as it is now, and the `README.md` was stating the incorrect version, so just a quick PR to fix that.
=> Minor documentation fixes

.gitignore
`clangd` reads the `/compile_commands.json` file and provides IDEs such as VSCode with features like "go to definition", "find all references", hints, etc. It creates a directory called `.cache` in the package root, and unfortuantely that's picked up by git, which means that when I try to work on the project in VSCode, it asks me to commit all of these cache files. `clangd` can be (and is) used by other IDEs as well, so it will help with those too; though I do not have experience with others.
=> Add the clangd cache to the gitignore

src/filters/mirror.c
This filter allows you to mirror voxels in a selected box, or the whole layer, and across all layers or only one layer. Very similar to the "wrap voxels" filter, except this one does mirroring.
=> Add a filter to mirror voxels

doc/cla/individual/calebh.md, src/formats/vxl.c
This pull request replaces the old buggy loader for the VXL file format. The exporter remains unchanged since it does not seem to corrupt the VXL files. This fixes issue #408.
The old loader was unable to import many VXL files and would frequently results in missing blocks and exposed internal blocks.
Note that this importer is not compatible with Jagex version AOS maps, which differ from AOS classic maps.
=> Fixed buggy VXL Importer
